# Generated by Django 3.2.7 on 2021-10-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='published',
            new_name='publish',
        ),
    ]
