# Generated by Django 3.2.7 on 2021-10-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
