# Generated by Django 3.2.7 on 2021-10-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='cmnt',
        ),
    ]
