# Generated by Django 3.2.7 on 2021-10-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
    ]
